"""add_admin_module

Revision ID: 1ae2c27b40b7
Revises: d4e5f6a7b8c9
Create Date: 2026-05-28 15:07:00.581996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1ae2c27b40b7'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dress_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dress_category_slug'), 'dress_category', ['slug'], unique=True)
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_slug'), 'city', ['slug'], unique=True)
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_type_slug'), 'event_type', ['slug'], unique=True)

    # Seed initial data
    city_table = sa.table('city',
        sa.column('slug', sa.String),
        sa.column('display_name', sa.String),
        sa.column('latitude', sa.Float),
        sa.column('longitude', sa.Float)
    )
    op.bulk_insert(city_table, [
        {"slug": "berlin", "display_name": "Berlin", "latitude": 52.5200, "longitude": 13.4050},
        {"slug": "munich", "display_name": "Munich", "latitude": 48.1351, "longitude": 11.5820},
        {"slug": "hamburg", "display_name": "Hamburg", "latitude": 53.5511, "longitude": 9.9937},
        {"slug": "cologne", "display_name": "Cologne", "latitude": 50.9375, "longitude": 6.9603},
        {"slug": "frankfurt", "display_name": "Frankfurt", "latitude": 50.1109, "longitude": 8.6821},
        {"slug": "stuttgart", "display_name": "Stuttgart", "latitude": 48.7758, "longitude": 9.1829},
        {"slug": "dusseldorf", "display_name": "Dusseldorf", "latitude": 51.2277, "longitude": 6.7735},
        {"slug": "leipzig", "display_name": "Leipzig", "latitude": 51.3397, "longitude": 12.3731},
        {"slug": "dresden", "display_name": "Dresden", "latitude": 51.0504, "longitude": 13.7373},
        {"slug": "nuremberg", "display_name": "Nuremberg", "latitude": 49.4521, "longitude": 11.0767},
        {"slug": "bremen", "display_name": "Bremen", "latitude": 53.0793, "longitude": 8.8017},
        {"slug": "hannover", "display_name": "Hannover", "latitude": 52.3759, "longitude": 9.7320},
        {"slug": "dortmund", "display_name": "Dortmund", "latitude": 51.5136, "longitude": 7.4653},
        {"slug": "essen", "display_name": "Essen", "latitude": 51.4556, "longitude": 7.0116},
        {"slug": "mannheim", "display_name": "Mannheim", "latitude": 49.4875, "longitude": 8.4660},
    ])

    event_type_table = sa.table('event_type',
        sa.column('slug', sa.String),
        sa.column('display_name', sa.String)
    )
    op.bulk_insert(event_type_table, [
        {"slug": "business", "display_name": "Business"},
        {"slug": "casual", "display_name": "Casual"},
        {"slug": "smart_casual", "display_name": "Smart Casual"},
        {"slug": "formal", "display_name": "Formal"},
        {"slug": "outdoor", "display_name": "Outdoor"},
        {"slug": "party", "display_name": "Party"},
        {"slug": "sports", "display_name": "Sports"},
        {"slug": "date_night", "display_name": "Date Night"},
        {"slug": "other", "display_name": "Other"},
    ])

    dress_category_table = sa.table('dress_category',
        sa.column('slug', sa.String),
        sa.column('display_name', sa.String)
    )
    op.bulk_insert(dress_category_table, [
        {"slug": "top", "display_name": "Top"},
        {"slug": "bottom", "display_name": "Bottom"},
        {"slug": "outerwear", "display_name": "Outerwear"},
        {"slug": "shoes", "display_name": "Shoes"},
        {"slug": "accessory", "display_name": "Accessory"},
        {"slug": "dress", "display_name": "Dress"},
        {"slug": "underwear", "display_name": "Underwear"},
        {"slug": "bag", "display_name": "Bag"},
        {"slug": "hat", "display_name": "Hat"},
        {"slug": "socks", "display_name": "Socks"},
        {"slug": "other", "display_name": "Other"},
    ])

    # Add temporary nullable columns
    op.add_column('dress', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('event_type_id', sa.Integer(), nullable=True))

    # Migrate existing data using subqueries
    op.execute(
        "UPDATE dress SET category_id = COALESCE("
        "  (SELECT id FROM dress_category WHERE dress_category.slug = dress.category),"
        "  (SELECT id FROM dress_category WHERE dress_category.slug = 'other')"
        ")"
    )
    op.execute(
        "UPDATE event SET city_id = COALESCE("
        "  (SELECT id FROM city WHERE city.slug = event.city),"
        "  (SELECT id FROM city WHERE city.slug = 'berlin')"
        ")"
    )
    op.execute(
        "UPDATE event SET event_type_id = COALESCE("
        "  (SELECT id FROM event_type WHERE event_type.slug = event.event_type),"
        "  (SELECT id FROM event_type WHERE event_type.slug = 'other')"
        ")"
    )

    # Perform batch alterations (drop old columns, make new ones non-nullable, set foreign keys)
    with op.batch_alter_table('dress', schema=None) as batch_op:
        batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('user_notes',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('colors',
                   existing_type=sqlite.JSON(),
                   nullable=True)
        batch_op.alter_column('season_suitability',
                   existing_type=sqlite.JSON(),
                   nullable=True)
        batch_op.alter_column('style',
                   existing_type=sqlite.JSON(),
                   nullable=True)
        batch_op.alter_column('occasion_tags',
                   existing_type=sqlite.JSON(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_dress_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_dress_category_id', 'dress_category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('city_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('event_type_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('notes',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.create_foreign_key('fk_event_city_id', 'city', ['city_id'], ['id'])
        batch_op.create_foreign_key('fk_event_event_type_id', 'event_type', ['event_type_id'], ['id'])
        batch_op.drop_column('city')
        batch_op.drop_column('event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=10), nullable=True))

    op.execute(
        "UPDATE event SET city = COALESCE("
        "  (SELECT slug FROM city WHERE city.id = event.city_id),"
        "  'berlin'"
        ")"
    )
    op.execute(
        "UPDATE event SET event_type = COALESCE("
        "  (SELECT slug FROM event_type WHERE event_type.id = event.event_type_id),"
        "  'other'"
        ")"
    )

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('city', nullable=False)
        batch_op.alter_column('event_type', nullable=False)
        batch_op.drop_constraint('fk_event_city_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_event_type_id', type_='foreignkey')
        batch_op.drop_column('event_type_id')
        batch_op.drop_column('city_id')
        batch_op.alter_column('notes',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)

    with op.batch_alter_table('dress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=9), nullable=True))

    op.execute(
        "UPDATE dress SET category = ("
        "  SELECT slug FROM dress_category WHERE dress_category.id = dress.category_id"
        ")"
    )

    with op.batch_alter_table('dress', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dress_category_id', type_='foreignkey')
        batch_op.drop_index('ix_dress_category_id')
        batch_op.drop_column('category_id')
        batch_op.alter_column('occasion_tags',
                   existing_type=sqlite.JSON(),
                   nullable=False)
        batch_op.alter_column('style',
                   existing_type=sqlite.JSON(),
                   nullable=False)
        batch_op.alter_column('season_suitability',
                   existing_type=sqlite.JSON(),
                   nullable=False)
        batch_op.alter_column('colors',
                   existing_type=sqlite.JSON(),
                   nullable=False)
        batch_op.alter_column('user_notes',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('description',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)

    op.drop_index(op.f('ix_event_type_slug'), table_name='event_type')
    op.drop_table('event_type')
    op.drop_index(op.f('ix_city_slug'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_dress_category_slug'), table_name='dress_category')
    op.drop_table('dress_category')
    # ### end Alembic commands ###

